import { defineSchema, defineTable } from 'convex/server'
import { authTables } from '@convex-dev/auth/server'
import { v } from 'convex/values'

const role = v.union(v.literal('president'),v.literal('admin'),v.literal('staff'),v.literal('protocol'),v.literal('press'))
const accountStatus = v.union(v.literal('pending'),v.literal('active'),v.literal('suspended'),v.literal('revoked'))
const publicationStatus = v.union(v.literal('draft'),v.literal('review'),v.literal('approved'),v.literal('published'),v.literal('archived'))

export default defineSchema({
  ...authTables,
  staffProfiles: defineTable({ userId:v.optional(v.id('users')), email:v.string(), fullName:v.string(), preferredName:v.optional(v.string()), employeeId:v.optional(v.string()), phone:v.optional(v.string()), jobTitle:v.optional(v.string()), office:v.optional(v.string()), department:v.optional(v.string()), supervisor:v.optional(v.string()), workLocation:v.optional(v.string()), employmentType:v.optional(v.string()), startDate:v.optional(v.string()), role, status:v.optional(accountStatus), active:v.boolean(), securityPolicyAcceptedAt:v.optional(v.number()), createdAt:v.number(), updatedAt:v.number() }).index('by_user',['userId']).index('by_email',['email']).index('by_employee_id',['employeeId']),
  staffInvitations: defineTable({ codeHash:v.string(), email:v.string(), employeeId:v.optional(v.string()), intendedRole:role, office:v.optional(v.string()), department:v.optional(v.string()), expiresAt:v.number(), createdBy:v.id('users'), createdAt:v.number(), usedAt:v.optional(v.number()), usedBy:v.optional(v.id('users')), revokedAt:v.optional(v.number()), revokedBy:v.optional(v.id('users')) }).index('by_code_hash',['codeHash']).index('by_email',['email']),
  privilegedApprovals: defineTable({ action:v.string(), entity:v.string(), entityId:v.optional(v.string()), requestedBy:v.id('users'), requestedAt:v.number(), status:v.union(v.literal('pending'),v.literal('approved'),v.literal('rejected'),v.literal('cancelled')), reviewedBy:v.optional(v.id('users')), reviewedAt:v.optional(v.number()), reason:v.optional(v.string()) }).index('by_status',['status']).index('by_requester',['requestedBy']),

  executiveOffices: defineTable({ kind:v.union(v.literal('vice_president'),v.literal('prime_minister')), name:v.string(), mandate:v.optional(v.string()), functions:v.optional(v.string()), leaderName:v.optional(v.string()), leaderTitle:v.optional(v.string()), phone:v.optional(v.string()), email:v.optional(v.string()), website:v.optional(v.string()), officeAddress:v.optional(v.string()), status:publicationStatus, publishedAt:v.optional(v.number()), createdBy:v.id('users'), updatedBy:v.id('users'), createdAt:v.number(), updatedAt:v.number() }).index('by_kind',['kind']).index('by_status',['status']),
  executiveDepartments: defineTable({ name:v.string(), shortName:v.optional(v.string()), mandate:v.optional(v.string()), functions:v.optional(v.string()), leaderName:v.optional(v.string()), leaderTitle:v.optional(v.string()), phone:v.optional(v.string()), email:v.optional(v.string()), website:v.optional(v.string()), officeAddress:v.optional(v.string()), sortOrder:v.optional(v.number()), status:publicationStatus, publishedAt:v.optional(v.number()), createdBy:v.id('users'), updatedBy:v.id('users'), createdAt:v.number(), updatedAt:v.number() }).index('by_status',['status']).index('by_name',['name']),

  executiveOrders: defineTable({ orderNumber:v.string(),title:v.string(),body:v.optional(v.string()),category:v.string(),issuedDate:v.optional(v.string()),status:v.string(),createdBy:v.optional(v.id('users')) }).index('by_status',['status']),
  appointments: defineTable({ appointeeName:v.string(),position:v.string(),institution:v.string(),appointmentType:v.string(),effectiveDate:v.string(),instrumentNumber:v.optional(v.string()),status:v.string(),notes:v.optional(v.string()),createdBy:v.id('users'),createdAt:v.number() }).index('by_status',['status']),
  honours: defineTable({ recipientName:v.string(),honourName:v.string(),category:v.string(),citation:v.optional(v.string()),ceremonyDate:v.optional(v.string()),status:v.string(),createdBy:v.id('users'),createdAt:v.number() }).index('by_status',['status']),
  pressStatements: defineTable({ headline:v.string(),body:v.string(),statementType:v.string(),releaseDate:v.optional(v.string()),status:v.string(),createdBy:v.optional(v.id('users')) }).index('by_status',['status']),
  stateFunctions: defineTable({ title:v.string(),functionType:v.string(),location:v.optional(v.string()),eventDate:v.string(),description:v.optional(v.string()),isPublic:v.boolean(),status:v.string(),createdBy:v.optional(v.id('users')) }).index('by_public_status',['isPublic','status']).index('by_status',['status']),
  petitions: defineTable({ referenceNumber:v.string(),petitionerName:v.string(),district:v.optional(v.string()),subject:v.string(),body:v.string(),routedTo:v.optional(v.string()),status:v.string(),responseSummary:v.optional(v.string()),receivedDate:v.string(),createdAt:v.number(),createdBy:v.id('users') }).index('by_status',['status']),
  stateVisits: defineTable({ counterpartCountry:v.string(),counterpartTitle:v.string(),direction:v.string(),visitType:v.string(),startDate:v.string(),endDate:v.optional(v.string()),agenda:v.optional(v.string()),status:v.string(),createdBy:v.id('users'),createdAt:v.number() }).index('by_status',['status']),
  milestones: defineTable({ category:v.string(),title:v.string(),description:v.optional(v.string()),year:v.optional(v.string()),status:v.string(),createdBy:v.optional(v.id('users')) }).index('by_status',['status']),
  legislation: defineTable({ billTitle:v.string(),billNumber:v.optional(v.string()),description:v.optional(v.string()),status:v.string(),actionDate:v.optional(v.string()),createdBy:v.optional(v.id('users')) }).index('by_status',['status']),
  galleryItems: defineTable({ title:v.string(),mediaType:v.string(),mediaUrl:v.string(),caption:v.optional(v.string()),category:v.optional(v.string()),status:v.string(),createdBy:v.optional(v.id('users')) }).index('by_status',['status']),
  youthPrograms: defineTable({ programType:v.string(),title:v.string(),description:v.optional(v.string()),deadline:v.optional(v.string()),applyLink:v.optional(v.string()),status:v.string(),createdBy:v.optional(v.id('users')) }).index('by_status',['status']),
  contactMessages: defineTable({ name:v.string(),email:v.string(),subject:v.string(),message:v.string(),status:v.string(),createdAt:v.number() }).index('by_status',['status']),
  visitorRequests: defineTable({ visitorName:v.string(),email:v.string(),phone:v.optional(v.string()),country:v.optional(v.string()),organization:v.optional(v.string()),visitCategory:v.string(),groupSize:v.number(),purpose:v.string(),preferredDate:v.string(),alternateDate:v.optional(v.string()),status:v.string(),referenceNumber:v.string(),createdAt:v.number() }).index('by_status',['status']),
  newsletterSubscribers: defineTable({ email:v.string(),subscribedAt:v.number(),unsubscribed:v.boolean() }).index('by_email',['email']),
  auditLog: defineTable({ userId:v.id('users'),action:v.string(),entity:v.string(),entityId:v.optional(v.string()),details:v.optional(v.string()),createdAt:v.number() }).index('by_created_at',['createdAt']).index('by_user',['userId']),
})
